logging:
  level:
    com:
     taiji:
       om:
        dao: DEBUG

server:
  port: 8080

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

   # servlet-path: /gz
    servlet-path: /toLogin


spring:

  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

    mode: HTML5
    jpa:
      hibernate:
        ddl_auto: update
        show_sql: true


  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource


    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver

      url: jdbc:mysql://localhost:3306/gz?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password:

      initial-size: 1
      min-idle: 1
      max-active: 20

      max-wait: 60000

      time-between-eviction-runs-millis: 60000

      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.taiji.gz.entity


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql









